server:
  port: 8761
spring:
  application:
    name: discovery-service
eureka:
  username: ${EUREKA_USERNAME:user}
  password: ${EUREKA_PASSWORD:1234}
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false